# Single Dimension Matrix using numpy library

In [1]:
import numpy as np
a=np.array([5,6,7,8])
a

array([5, 6, 7, 8])

In [2]:
type(a
    )

numpy.ndarray

In [3]:
len(a)

4

In [4]:
a[0:]

array([5, 6, 7, 8])

# 2D array in python using numpy

In [6]:
import numpy as np
b=np.array([[2,3,4],[4,5,6],[6,6,7]])
b

array([[2, 3, 4],
       [4, 5, 6],
       [6, 6, 7]])

In [7]:
type(b)

numpy.ndarray

In [8]:
len(b)

3

In [9]:
#array([5,5,5])
b[0]

array([2, 3, 4])

In [10]:
b[0:
 ]

array([[2, 3, 4],
       [4, 5, 6],
       [6, 6, 7]])

# m-dimensional array use TensorFlow library used for AI Abd ML

In [13]:
c=np.array([[2,3,4],[4,5,6]])
c

array([[2, 3, 4],
       [4, 5, 6]])

In [15]:
d=np.array([[5,5,5],[5,5,5]])
d

array([[5, 5, 5],
       [5, 5, 5]])

# Single Dimension Array using numpy

In [16]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

### Multidimensional Matrix or array or table in python using numpy

In [17]:
b1=np.array([[1,2,3],[4,5,6]])
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Zero fill single dimensional array using builtin function zeros

In [18]:
import numpy as np
zerofill=np.zeros(2)
zerofill

array([0., 0.])

In [20]:
import numpy as np
zerofill=np.zeros(2)
zerofill

array([0., 0.])

# one fill single dimensional array usimg numpy library

In [21]:
one=np.ones(3)
one

array([1., 1., 1.])

# empty arrays/matrix using numpy library builtin function empty

In [22]:
emp=np.empty(3)
emp

array([1., 1., 1.])

# specific data type array in numpy library


In [24]:
specific=np.ones(5, dtype=np.int8)
specific

array([1, 1, 1, 1, 1], dtype=int8)

In [26]:
float_array=np.ones(5,dtype=np.float64)
float_array

array([1., 1., 1., 1., 1.])

In [28]:
float_array=np.ones(5,dtype=np.float32)
float_array

array([1., 1., 1., 1., 1.], dtype=float32)

# 2d Matrix or arrays using numpy builtin function

In [29]:
twoDA=np.zeros((3,4))
twoDA

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
twoDones=np.ones((4,4))
twoDones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
twoDones=np.ones((4,4), dtype=np.int8)
twoDones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [33]:
twoDzero=np.zeros((3,4), dtype=np.int8)
twoDzero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [34]:
twoDzero=np.zeros((3,4))
twoDzero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# making three dimenisional array

In [37]:
threeDarr=np.arange(24).reshape(2, 3, 4)
threeDarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
threeDarr=np.arange(24).reshape(2, 3, 4)
threeDarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])